export const DOMAIN_ARGUMENT_INVALID = 'DOMAIN_GENERIC_ARGUMENT_INVALID';
export const DOMAIN_ARGUMENT_OUT_OF_RANGE =
  'DOMAIN_GENERIC_ARGUMENT_OUT_OF_RANGE';
export const DOMAIN_ARGUMENT_NOT_PROVIDED =
  'DOMAIN_GENERIC_ARGUMENT_NOT_PROVIDED';
export const DOMAIN_NOT_FOUND = 'DOMAIN_GENERIC_NOT_FOUND';
export const DOMAIN_CONFLICT = 'DOMAIN_GENERIC_CONFLICT';
export const DOMAIN_INTERNAL_SERVER_ERROR =
  'DOMAIN_GENERIC_INTERNAL_SERVER_ERROR';
export const BROKEN_RULES_EXCEPTION = 'BROKEN_RULES_EXCEPTION';
export const DOMAIN_COMMAND_HANDLER_NOT_FOUND =
  'DOMAIN_COMMAND_HANDLER_NOT_FOUND';
export const DOMAIN_INVALID_COMMAND_HANDLER = 'DOMAIN_INVALID_COMMAND_HANDLER';
export const DOMAIN_INVALID_SAGA = 'DOMAIN_INVALID_SAGA';
export const DOMAIN_CRITERIA = 'DOMAIN_CRITERIA';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
