export const DOMAIN_ARGUMENT_INVALID = 'DOMAIN_GENERIC_ARGUMENT_INVALID';
export const DOMAIN_ARGUMENT_OUT_OF_RANGE =
  'DOMAIN_GENERIC_ARGUMENT_OUT_OF_RANGE';
export const DOMAIN_ARGUMENT_NOT_PROVIDED =
  'DOMAIN_GENERIC_ARGUMENT_NOT_PROVIDED';
export const DOMAIN_NOT_FOUND = 'DOMAIN_GENERIC_NOT_FOUND';
export const DOMAIN_CONFLICT = 'DOMAIN_GENERIC_CONFLICT';
export const DOMAIN_INTERNAL_SERVER_ERROR =
  'DOMAIN_GENERIC_INTERNAL_SERVER_ERROR';
